site_name: RADocs 
site_description: RetroAchievements.org Documentation Project 
site_url: https://docs.retroachievements.org/

repo_name: RetroAchievements/docs
repo_url: https://github.com/RetroAchievements/docs/wiki/
# XXX: If you do not want any "edit URL link" displayed on your pages,
# then set edit_uri to an empty string to disable the automatic setting.
edit_uri: https://retroachievements.org/wiki-edit-redirect.php?page=

docs_dir: docs.wiki
site_dir: no-material-site

# dev_addr 
# Determines the address used when running mkdocs serve. 
# Must be of the format IP:PORT. 
dev_addr: '127.0.0.1:8000'
nav:
  - General:
    - index.md
    - RetroAchievements Manifesto: RetroAchievements-Manifesto.md
  - Portugues:
    - Introdução: Home-pt_BR.md
    - Geral:
      - Manifesto RetroAchievements: RetroAchievements-Manifesto-pt_BR.md

